### ISSUE TITLE
gsutil broken within Docker image

### ISSUE THREAD

**Issue by dpark01** [broadinstitute/viral-ngs-deploy#51]
I'm finding that I can't call gsutil from within the Docker image. I see that there are attempts to install the GCP SDK and add it to the path, but I get [errors like this](https://storage.cloud.google.com/sabeti-lab/dpark/dsub-test/logs/reports--dpark--171017-152742-94.log) when I attempt to dsub the 1.18.0 image and use `--input-recursive` or `--output-recursive`. Apparently, that's the only time it really needs gsutil inside the container, and if it doesn't see it, it tries to auto-install it via apt-get, but apt-get fails if we [blow away its "lists" directory](https://github.com/broadinstitute/viral-ngs-deploy/blob/master/docker/Dockerfile#L38). I am successfully able to use `--input` and `--output` and execute code, so I think everything else probably works.

Example error log:
```
E: command failed: /tmp/ggp-062979599: line 16: type: gsutil: not found
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
 (exit status 100)
```

**Comment by tomkinsc** [comment]
This may be a byproduct of the docker export | docker import. I’ll have to
investigate.

**Comment by dpark01** [comment]
Actually I think it's just a matter of the `PATH`, though I'm not familiar enough with `gosu` to know whether I can just add it to the `PATH` or if I have to do something more.

This works for me:
```
docker run broadinstitute/viral-ngs:1.18.0 /opt/google-cloud-sdk/bin/gsutil --version
```

This fails (and `dsub` needs this to work):
```
docker run broadinstitute/viral-ngs:1.18.0 gsutil --version
```

**Comment by tomkinsc** [comment]
I've confirmed this is related to the `docker export | docker import` thinning. If I build the image locally and enter a shell via `docker run --rm -ti --entrypoint=/bin/bash <image_ID> -s` gsutil is available on the built image, but not the thinned image. That makes me wonder how else the image may be different. Maybe it is not worth the 150MB?

**Comment by dpark01** [comment]
For now, I agree

**Comment by dpark01** [comment]
Let's leave it out for now
